services:
  network-assistant:
    build: .

    network_mode: host

    environment:
      NETWORK_ASSISTANT_EXECUTE: "${NETWORK_ASSISTANT_EXECUTE:-0}"

    cap_add:
      - NET_ADMIN
      - NET_RAW

    stdin_open: true
    tty: true
